### ISSUE TITLE
mongo-express no go up.

### ISSUE THREAD

**Issue by chpiero** [chupati/farm-part-2#2]
Hi,
when run docker-compose up have this error:

`farm-part-2_mongo-express_1 exited with code 0`

and mongo-express no go up.

thanks

**Comment by chupati** [comment]
@chpiero . Thank you for trying the project. Could you please post the messages surrounding the "exited" message you posted?

**Comment by chupati** [comment]
@chpiero . I updated the README. The mongo-express service is expected to fail until MongoDB is finally established. Was this not the case for you? At the end of the running logs you should have finally seen the entry below.

mongo-express_1  | Welcome to mongo-express
mongo-express_1  | ------------------------
mongo-express_1  | 
mongo-express_1  | 
mongo-express_1  | Mongo Express server listening at http://0.0.0.0:8081
mongo-express_1  | Server is open to allow connections from anyone (0.0.0.0)
mongo-express_1  | basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!

**Comment by chpiero** [comment]
> @chpiero . Thank you for trying the project. Could you please post the messages surrounding the "exited" message you posted?

mongo-express_1  | Welcome to mongo-express
mongo-express_1  | ------------------------
mongo-express_1  |
mongo-express_1  |
mongo-express_1  | (node:8) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
mongo-express_1  | Could not connect to database using connectionString: mongodb://mongo:27017"
mongo-express_1  | (node:8) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongo:27017] on first connect [Error: connect ECONNREFUSED 172.20.0.3:27017
mongo-express_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
mongo-express_1  |   name: 'MongoNetworkError'
mongo-express_1  | }]
mongo-express_1  |     at Pool.<anonymous> (/node_modules/mongodb/lib/core/topologies/server.js:441:11)
mongo-express_1  |     at Pool.emit (events.js:314:20)
mongo-express_1  |     at /node_modules/mongodb/lib/core/connection/pool.js:564:14
mongo-express_1  |     at /node_modules/mongodb/lib/core/connection/pool.js:999:11
mongo-express_1  |     at /node_modules/mongodb/lib/core/connection/connect.js:32:7
mongo-express_1  |     at callback (/node_modules/mongodb/lib/core/connection/connect.js:283:5)
mongo-express_1  |     at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connect.js:313:7)
mongo-express_1  |     at Object.onceWrapper (events.js:421:26)
mongo-express_1  |     at Socket.emit (events.js:314:20)
mongo-express_1  |     at emitErrorNT (internal/streams/destroy.js:92:8)
mongo-express_1  |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
mongo-express_1  |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
mongo-express_1  | (node:8) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
mongo-express_1  | (node:8) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
**farm-part-2_mongo-express_1 exited with code 0**
mongo_1          | {"t":{"$date":"2021-08-09T22:37:39.537+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1628548659:537884][1:0x7f175a05fc80], txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Main recovery loop: starting at 4/22784 to 5/256"}}
mongo_1          | {"t":{"$date":"2021-08-09T22:37:39.541+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1628548659:541460][1:0x7f175a05fc80], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 4 through 5"}}

**Comment by chupati** [comment]
Thank you @chpiero . Could you please pull the latest version. I see I was using version 0.54 of mongo-express. So I added that version in the docker-compose.yml file. You will need to type "docker-compose down" before you run "docker-compose up" to pull the updated image.

**Comment by chpiero** [comment]
Thanks now work.
