### ISSUE TITLE
Fastapi no go up

### ISSUE THREAD

**Issue by chpiero** [chupati/farm-part-2#3]
Sorry but also fastapi doesn't work. The error is:

`ModuleNotFoundError: No module named 'app'`

**Comment by chupati** [comment]
Thank you @chpiero. What are the errors that surround this message?

**Comment by chpiero** [comment]
> Thank you @chpiero. What are the errors that surround this message?

fastapi_1        | Traceback (most recent call last):
fastapi_1        |   File "/usr/local/bin/uvicorn", line 8, in <module>
fastapi_1        |     sys.exit(main())
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
fastapi_1        |     return self.main(*args, **kwargs)
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
fastapi_1        |     rv = self.invoke(ctx)
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
fastapi_1        |     return ctx.invoke(self.callback, **ctx.params)
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
fastapi_1        |     return callback(*args, **kwargs)
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 362, in main
fastapi_1        |     run(**kwargs)
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 386, in run
fastapi_1        |     server.run()
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 49, in run
fastapi_1        |     loop.run_until_complete(self.serve(sockets=sockets))
fastapi_1        |   File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 56, in serve
fastapi_1        |     config.load()
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 308, in load
fastapi_1        |     self.loaded_app = import_from_string(self.app)
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 23, in import_from_string
fastapi_1        |     raise exc from None
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 20, in import_from_string
fastapi_1        |     module = importlib.import_module(module_str)
fastapi_1        |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
fastapi_1        |     return _bootstrap._gcd_import(name[level:], package, level)
fastapi_1        |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
fastapi_1        |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
fastapi_1        |   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
fastapi_1        |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
fastapi_1        |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
fastapi_1        |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
fastapi_1        |   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
fastapi_1        | ModuleNotFoundError: No module named 'app'
**farm-part-2_fastapi_1 exited with code 1**

**Comment by chupati** [comment]
Thank @chpiero ! I appreciate your input. I added a PYTHONPATH environment variable to the docker-compose.yml file. Could you please pull the latest changes and try again?

**Comment by chpiero** [comment]
> Thank @chpiero ! I appreciate your input. I added a PYTHONPATH environment variable to the docker-compose.yml file. Could you please pull the latest changes and try again?

same error

**Comment by chupati** [comment]
@chpiero . What operating system are you using? I'm going to attempt to duplicate your issue on a matching system.

**Comment by chpiero** [comment]
> @chpiero . What operating system are you using? I'm going to attempt to duplicate your issue on a matching system.

OSX 10.15.7 (Catalina)
Docker CE 20.10.7

**Comment by chupati** [comment]
@chpiero . Can you please run the following commands?

docker-compose down
docker-compose build --no-cache fastapi
docker-compose up

**Comment by chpiero** [comment]
> @chpiero . Can you please run the following commands?
> 
> docker-compose down
> docker-compose build --no-cache fastapi
> docker-compose up

I tried but always the same error I also deleted everything and redone the clone ... but always the same error

**Comment by chupati** [comment]
@chpiero . What do you see when you type the command below? I am trying to see if the "fastapi" directory is even mounted to your container.
docker-compose run fastapi ls /app

**Comment by chpiero** [comment]
> docker-compose run fastapi ls /app

[+] Running 1/1
 ⠿ Network farm-part-2_default  Created                                                                                                                                                                                                                     0.2s
ls: reading directory '/app': Operation not permitted

**Comment by chupati** [comment]
Thank you. If you use "sudo" with the "up" command do you get different results? There seems to be an issue with the volume being mapped properly. I think. Try:

sudo docker-compose down
sudo docker-compose up

**Comment by chpiero** [comment]
> Thank you. If you use "sudo" with the "up" command do you get different results? There seems to be an issue with the volume being mapped properly. I think. Try:
> 
> sudo docker-compose down
> sudo docker-compose up

same error

**Comment by chupati** [comment]
Thank you again @chpiero for assisting me. I added an "rm -rf /app" app line in the FastAPI build file. Maybe the permissions error will go away if the creation of "/app" is left up to Docker Compose.

Could you pull the latest changes and run the commands below?

docker-compose down
docker-compose build --no-cache fastapi
docker-compose up

**Comment by chupati** [comment]
@chpiero . If you still get an error, do the commands below behave any differently? They are "docker" commands with "compose" parameters instead of "docker-compose".

docker compose down
docker compose up

**Comment by chpiero** [comment]
> docker compose up


i also deleted the containers and cleaned docker cache and restarted everything with both command  "docker-compose" and "docker compose", but nothing always the same error

**Comment by chupati** [comment]
@chpiero . I am interested in seeing your container's folder permissions. What does it say when you type the following command?

docker-compose run fastapi ls -l /

Also, what are the permissions of the host folder "fastapi"? In the project directory, you can type the command below. Are the folder permissions set to at least read, write? ("rw-rw-r") and is the folder owner you (not "root")?

ls -l ./

**Comment by chpiero** [comment]
> ls -l ./

the output of `docker-compose run fastapi ls -l /`:

drwxr-xr-x   4 root root  128 Aug 11 21:03 app
drwxr-xr-x   1 root root 4096 Feb  9  2021 bin
drwxr-xr-x   2 root root 4096 Jan 30  2021 boot
drwxr-xr-x   5 root root  360 Aug 11 21:24 dev
drwxr-xr-x   1 root root 4096 Aug 11 21:24 etc
drwxr-xr-x   2 root root 4096 Jan 30  2021 home
drwxr-xr-x   1 root root 4096 Feb  9  2021 lib
drwxr-xr-x   2 root root 4096 Feb  8  2021 lib64
drwxr-xr-x   2 root root 4096 Feb  8  2021 media
drwxr-xr-x   2 root root 4096 Feb  8  2021 mnt
drwxr-xr-x   2 root root 4096 Feb  8  2021 opt
dr-xr-xr-x 183 root root    0 Aug 11 21:24 proc
drwx------   1 root root 4096 Aug 11 21:08 root
drwxr-xr-x   3 root root 4096 Feb  8  2021 run
drwxr-xr-x   1 root root 4096 Feb  9  2021 sbin
drwxr-xr-x   2 root root 4096 Feb  8  2021 srv
dr-xr-xr-x  13 root root    0 Aug 11 21:24 sys
drwxrwxrwt   1 root root 4096 Aug 11 21:08 tmp
drwxr-xr-x   1 root root 4096 Feb  8  2021 usr
drwxr-xr-x   1 root root 4096 Feb  8  2021 var


Instead the permissions of the host folder is :

-rw-r--r--  1 piero  staff   1,0K 11 Ago 23:03 LICENSE
-rw-r--r--  1 piero  staff   422B 11 Ago 23:03 README.md
drwxr-xr-x  4 piero  staff   128B 11 Ago 23:05 data/
-rw-r--r--  1 piero  staff   870B 11 Ago 23:03 docker-compose.yml
drwxr-xr-x  4 piero  staff   128B 11 Ago 23:03 fastapi/
-rw-r--r--  1 piero  staff   269B 11 Ago 23:03 fastapi.dockerfile

i try to impose chmod 777 fastapi and subdir but nothing doesn't work again same error

**Comment by chupati** [comment]
@chpiero . I do notice the "fastapi" directory on your host is only 128B. I believe the "fastapi/app/main.py" file alone is at least 4K.

Can you remove your "fastapi-part-2" cloned repo on your machine and clone it again?

**Comment by chpiero** [comment]
> @chpiero . I do notice the "fastapi" directory on your host is only 128B. I believe the "fastapi/app/main.py" file alone is at least 4K.
> 
> Can you remove your "fastapi-part-2" cloned repo on your machine and clone it again?

i did what you told me but main.py is 1K

**Comment by chpiero** [comment]
> > @chpiero . I do notice the "fastapi" directory on your host is only 128B. I believe the "fastapi/app/main.py" file alone is at least 4K.
> > Can you remove your "fastapi-part-2" cloned repo on your machine and clone it again?
> 
> i did what you told me but main.py is 1K

i clone it but the fastapi dir is 128B...you can try it

i checked the code (main.py) in my computer with the one on github, it seems to be the same

**Comment by chupati** [comment]
Thank you @chpiero . I meant to say 1.4K on my machine. But it sounds close. My "fastapi" folder is 4.0K. But if the contents of your "fastapi/app/main.py" file look the same then that should be fine?

Your docker stack still will not spin up after re-cloning?

**Comment by chpiero** [comment]
> Your docker stack still will not spin up after re-cloning?

you could explain yourself better, I restarted my docker do the cloning but the error persists

**Comment by chupati** [comment]
After running the following commands, do you still get the error?

1. Remove the cloned farm-part-2 repo on your machine
rm -rf farm-part-2

2. Re-clone the git repo
git clone git@github.com:chupati/farm-part-2.git

3. Go to your repo directory
cd farm-part-2

4. Run your docker compose stack.
docker-compose up

**Comment by chpiero** [comment]
> 4\. docker-compose up

yes i still have the same error

**Comment by chupati** [comment]
Thank you @chpiero ! Can you please post everything that occurs after typing "docker-compose up"? I am not able to reproduce this issue on my Mac. But, I want to see if notice anything occurring before "fastapi" breaks.

**Comment by chpiero** [comment]
> Thank you @chpiero ! Can you please post everything that occurs after typing "docker-compose up"? I am not able to reproduce this issue on my Mac. But, I want to see if notice anything occurring before "fastapi" breaks.

Attaching to fastapi_1, mongo-express_1, mongo_1
mongo_1          | {"t":{"$date":"2021-08-11T22:27:07.030+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"-","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:07.032+00:00"},"s":"I",  "c":"NETWORK",  "id":4915701, "ctx":"-","msg":"Initialized wire specification","attr":{"spec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":13},"incomingInternalClient":{"minWireVersion":0,"maxWireVersion":13},"outgoing":{"minWireVersion":0,"maxWireVersion":13},"isInternalClient":true}}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:07.035+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:07.035+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:07.037+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:07.037+00:00"},"s":"I",  "c":"REPL",     "id":5123008, "ctx":"main","msg":"Successfully registered PrimaryOnlyService","attr":{"service":"TenantMigrationDonorService","ns":"config.tenantMigrationDonors"}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:07.037+00:00"},"s":"I",  "c":"REPL",     "id":5123008, "ctx":"main","msg":"Successfully registered PrimaryOnlyService","attr":{"service":"TenantMigrationRecipientService","ns":"config.tenantMigrationRecipients"}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:07.038+00:00"},"s":"I",  "c":"CONTROL",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"09b8817bd59f"}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:07.039+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"5.0.2","gitVersion":"6d9ec525e78465dcecadcff99cce953d380fedc8","openSSLVersion":"OpenSSL 1.1.1f  31 Mar 2020","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu2004","distarch":"x86_64","target_arch":"x86_64"}}}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:07.039+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"20.04"}}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:07.039+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"*"},"security":{"authorization":"enabled"}}}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:07.048+00:00"},"s":"I",  "c":"STORAGE",  "id":22270,   "ctx":"initandlisten","msg":"Storage engine to use detected by data files","attr":{"dbpath":"/data/db","storageEngine":"wiredTiger"}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:07.051+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=3469M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),builtin_extension_config=(zstd=(compression_level=6)),file_manager=(close_idle_time=600,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress,compact_progress],"}}
fastapi_1        | Traceback (most recent call last):
fastapi_1        |   File "/usr/local/bin/uvicorn", line 8, in <module>
fastapi_1        |     sys.exit(main())
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
fastapi_1        |     return self.main(*args, **kwargs)
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
fastapi_1        |     rv = self.invoke(ctx)
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
fastapi_1        |     return ctx.invoke(self.callback, **ctx.params)
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
fastapi_1        |     return callback(*args, **kwargs)
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 362, in main
fastapi_1        |     run(**kwargs)
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 386, in run
fastapi_1        |     server.run()
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 49, in run
fastapi_1        |     loop.run_until_complete(self.serve(sockets=sockets))
fastapi_1        |   File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 56, in serve
fastapi_1        |     config.load()
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 308, in load
fastapi_1        |     self.loaded_app = import_from_string(self.app)
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 23, in import_from_string
fastapi_1        |     raise exc from None
fastapi_1        |   File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 20, in import_from_string
fastapi_1        |     module = importlib.import_module(module_str)
fastapi_1        |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
fastapi_1        |     return _bootstrap._gcd_import(name[level:], package, level)
fastapi_1        |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
fastapi_1        |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
fastapi_1        |   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
fastapi_1        |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
fastapi_1        |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
fastapi_1        |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
fastapi_1        |   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
**fastapi_1        | ModuleNotFoundError: No module named 'app'
fastapi_1 exited with code 1**
mongo_1          | {"t":{"$date":"2021-08-11T22:27:07.603+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1628720827:603562][1:0x7f29bf4cdc80], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 2 through 3"}}
mongo-express_1  | /docker-entrypoint.sh: connect: Connection refused
mongo-express_1  | /docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Connection refused
mongo_1          | {"t":{"$date":"2021-08-11T22:27:08.406+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1628720828:406934][1:0x7f29bf4cdc80], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 3 through 3"}}
mongo-express_1  | Wed Aug 11 22:27:08 UTC 2021 retrying to connect to mongo:27017 (2/5)
mongo-express_1  | /docker-entrypoint.sh: connect: Connection refused
mongo-express_1  | /docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Connection refused
mongo_1          | {"t":{"$date":"2021-08-11T22:27:09.191+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1628720829:191354][1:0x7f29bf4cdc80], txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Main recovery loop: starting at 2/5248 to 3/256"}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:09.258+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1628720829:258548][1:0x7f29bf4cdc80], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 2 through 3"}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:09.319+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1628720829:319742][1:0x7f29bf4cdc80], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 3 through 3"}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:09.353+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1628720829:353086][1:0x7f29bf4cdc80], txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Set global recovery timestamp: (0, 0)"}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:09.353+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1628720829:353162][1:0x7f29bf4cdc80], txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Set global oldest timestamp: (0, 0)"}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:09.354+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1628720829:354885][1:0x7f29bf4cdc80], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 1, snapshot max: 1 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 14"}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:09.370+00:00"},"s":"I",  "c":"STORAGE",  "id":4795906, "ctx":"initandlisten","msg":"WiredTiger opened","attr":{"durationMillis":2319}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:09.370+00:00"},"s":"I",  "c":"RECOVERY", "id":23987,   "ctx":"initandlisten","msg":"WiredTiger recoveryTimestamp","attr":{"recoveryTimestamp":{"$timestamp":{"t":0,"i":0}}}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:09.380+00:00"},"s":"I",  "c":"STORAGE",  "id":4366408, "ctx":"initandlisten","msg":"No table logging settings modifications are required for existing WiredTiger tables","attr":{"loggingEnabled":true}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:09.387+00:00"},"s":"I",  "c":"STORAGE",  "id":22262,   "ctx":"initandlisten","msg":"Timestamp monitor starting"}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:09.407+00:00"},"s":"I",  "c":"NETWORK",  "id":4915702, "ctx":"initandlisten","msg":"Updated wire specification","attr":{"oldSpec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":13},"incomingInternalClient":{"minWireVersion":0,"maxWireVersion":13},"outgoing":{"minWireVersion":0,"maxWireVersion":13},"isInternalClient":true},"newSpec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":13},"incomingInternalClient":{"minWireVersion":13,"maxWireVersion":13},"outgoing":{"minWireVersion":13,"maxWireVersion":13},"isInternalClient":true}}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:09.409+00:00"},"s":"I",  "c":"STORAGE",  "id":5071100, "ctx":"initandlisten","msg":"Clearing temp directory"}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:09.411+00:00"},"s":"I",  "c":"CONTROL",  "id":20536,   "ctx":"initandlisten","msg":"Flow Control is enabled on this deployment"}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:09.414+00:00"},"s":"I",  "c":"FTDC",     "id":20625,   "ctx":"initandlisten","msg":"Initializing full-time diagnostic data capture","attr":{"dataDirectory":"/data/db/diagnostic.data"}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:09.427+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"/tmp/mongodb-27017.sock"}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:09.427+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"0.0.0.0"}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:09.427+00:00"},"s":"I",  "c":"NETWORK",  "id":23016,   "ctx":"listener","msg":"Waiting for connections","attr":{"port":27017,"ssl":"off"}}
mongo-express_1  | Wed Aug 11 22:27:09 UTC 2021 retrying to connect to mongo:27017 (3/5)
mongo_1          | {"t":{"$date":"2021-08-11T22:27:09.659+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.24.0.2:47090","uuid":"f85796c7-3dcb-4140-b04f-fa74d5402e3e","connectionId":1,"connectionCount":1}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:09.660+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn1","msg":"Connection ended","attr":{"remote":"172.24.0.2:47090","uuid":"f85796c7-3dcb-4140-b04f-fa74d5402e3e","connectionId":1,"connectionCount":0}}
mongo-express_1  | Welcome to mongo-express
mongo-express_1  | ------------------------
mongo-express_1  | 
mongo-express_1  | 
mongo-express_1  | Mongo Express server listening at http://0.0.0.0:8081
mongo-express_1  | [31mServer is open to allow connections from anyone (0.0.0.0)[39m
mongo-express_1  | [31mbasicAuth credentials are "admin:pass", it is recommended you change this in your config.js![39m
mongo_1          | {"t":{"$date":"2021-08-11T22:27:10.220+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.24.0.2:47092","uuid":"e5a6ad72-81cf-42f1-9210-fd310581c9a0","connectionId":2,"connectionCount":1}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:10.228+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn2","msg":"client metadata","attr":{"remote":"172.24.0.2:47092","client":"conn2","doc":{"driver":{"name":"nodejs","version":"2.2.24"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.10.25-linuxkit"},"platform":"Node.js v12.22.4, LE, mongodb-core: 2.1.8"}}}
mongo-express_1  | Database connected
mongo_1          | {"t":{"$date":"2021-08-11T22:27:10.550+00:00"},"s":"I",  "c":"ACCESS",   "id":20250,   "ctx":"conn2","msg":"Authentication succeeded","attr":{"mechanism":"SCRAM-SHA-1","speculative":false,"principalName":"root","authenticationDatabase":"admin","remote":"172.24.0.2:47092","extraInfo":{}}}
mongo-express_1  | Admin Database connected
mongo_1          | {"t":{"$date":"2021-08-11T22:27:10.563+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.24.0.2:47094","uuid":"d694ce5c-554d-417b-a0e3-39f050e00c76","connectionId":3,"connectionCount":2}}
mongo_1          | {"t":{"$date":"2021-08-11T22:27:10.634+00:00"},"s":"I",  "c":"ACCESS",   "id":20250,   "ctx":"conn3","msg":"Authentication succeeded","attr":{"mechanism":"SCRAM-SHA-1","speculative":false,"principalName":"root","authenticationDatabase":"admin","remote":"172.24.0.2:47094","extraInfo":{}}}

**Comment by chupati** [comment]
@chpiero . I was able to reproduce the issue on my Mac!

Do you happen to have this repository located in your "Documents" folder or "Downloads" folder?

On my machine, I have to specifically grant Docker access to "Documents" or move it to my user root directory.

**Comment by chpiero** [comment]
> @chpiero . I was able to reproduce the issue on my Mac!
> 
> Do you happen to have this repository located in your "Documents" folder or "Downloads" folder?
> 
> On my machine, I have to specifically grant Docker access to "Documents" or move it to my user root directory.

  I never would have thought of such a thing. NOW, IT WORKS!!!!. I have all my development directories under Documents in a dev subdirectory and have never had these problems ... weird stuff. Thanks so much for the help. Will you make a part3 or develop on this repository to add the react part?
Thanks again

**Comment by chupati** [comment]
@chpiero . Awesome! I am glad you got it to work and I am very appreciative of all your input and help. Haha! It took a while for me to figure it out. I actually put all my stuff in a "Projects" directory of my user folder so I never noticed the issue. I am surprised the MongoDB service ran with no issues.

Yes. I will be developing a part 3 repository. Hopefully, I can get it out this week.

**Comment by chpiero** [comment]
> @chpiero . Awesome! I am glad you got it to work and I am very appreciative of all your input and help. Haha! It took a while for me to figure it out. I actually put all my stuff in a "Projects" directory of my user folder so I never noticed the issue. I am surprised the MongoDB service ran with no issues.
> 
> Yes. I will be developing a part 3 repository. Hopefully, I can get it out this week.

Perfect, I will stay tuned.

**Comment by chupati** [comment]
@chpiero . I added the repository that includes the React part of the FARM stack to 
https://github.com/chupati/farm-part-3

You need to set up a .env file in the root to store the "MONGO_USER" and "MONGO_PASSWORD" environment variables found in the "docker-compose.yml" file.

**Comment by chpiero** [comment]
@chupati thanks, as soon as I get back I try everything.
